handle frontend disconnects
tloncorp/landscape-apps pull request #1058
Opened 2022-11-01 18:29 UTC by patosullivan

fixes #1039

2022-11-01 20:44 UTC, patosullivan commented
We apparently often see calls to `/~/scry/hark/group//latest.json` that 404 and that'll cause the disconnect banner to show. @liam-fitzgerald @ryjm any idea why that is?

2022-11-01 20:51 UTC, patosullivan commented
Nevermind, this was a frontend issue. Pushing a fix.

2022-11-01 20:59 UTC, patosullivan commented
We still see 404s on calls to `/~/scry/hark/group/${flag}/latest.json` where we actually have a flag when viewing a group. I'm guessing it's because the group in question doesn't have any notifications. Should this return a 404? Seems like an empty response with a 200 would be better, but I don't know if there's some limitation preventing that. @arthyn @liam-fitzgerald @ryjm

2022-11-01 21:04 UTC, urcades approved these changes
Until we have a better sense of how to align the "universal" chrome interface across each of our apps, this banner is a perfect and hyper-obvious solve to surface the disconnect/reconnect interface.

2022-11-01 21:59 UTC, jamesacklin commented
> We still see 404s on calls to `/~/scry/hark/group/${flag}/latest.json` where we actually have a flag when viewing a group. I'm guessing it's because the group in question doesn't have any notifications. Should this return a 404? Seems like an empty response with a 200 would be better, but I don't know if there's some limitation preventing that. @arthyn @liam-fitzgerald @ryjm
> 
> Bringing this up because it causes our new subscription state to switch to "disconnected" briefly when loading a group, which causes the "disconnected" status bar to flash for ~300ms.

Well, we don't want that -- any advice for returning a 200 instead? @arthyn @liam-fitzgerald

2022-11-01 22:12 UTC, patosullivan commented
Hacky workaround: don't show a disconnect if it's a 404 on that type of path.

2022-11-01 22:24 UTC, arthyn commented
well I don't think scries should actually affect the subscription status at all so you can just remove it

2022-11-01 22:53 UTC, arthyn requested changes
This was a good way to do it, just a few changes, should help with the flashing.

2022-11-01 22:53 UTC, arthyn commented on ui/src/app.tsx
> +  const errorCount = useErrorCount();
doesn't seem like we're using this

2022-11-01 22:53 UTC, arthyn commented on ui/src/api.ts
> +    }
Revert, scries aren't passed through the same channel system so their errors don't have bearing on the connection status

2022-11-02 13:24 UTC, patosullivan commented on ui/src/app.tsx
> +  const errorCount = useErrorCount();
We're not using errorCount, yeah.

2022-11-02 20:07 UTC, arthyn approved these changes
lgtm

2022-11-02 20:08 UTC, merged