groups: avoid alien ships for now
tloncorp/landscape-apps pull request #1136
Opened 2022-11-11 06:54 UTC by ryjm

until runtime fix is in, to avoid ships getting into a bad state.

2022-11-17 00:16 UTC, liam-fitzgerald requested changes
Pls fix scry helper, else LGTM!

2022-11-17 00:16 UTC, liam-fitzgerald commented on desk/app/groups.hoon
> +  |*  [=mold care=term =desk =path]
This is a type-hole, you shouldn't polymorphism like this

2022-11-28 22:37 UTC, liam-fitzgerald approved these changes

2022-11-29 15:35 UTC, arthyn approved these changes

2022-11-29 15:36 UTC, merged