[wip] omnibus: scroller perf, devex enhancements
tloncorp/landscape-apps pull request #1197
Opened 2022-11-18 06:24 UTC by tomholford

# Context

This addresses #1187. It also includes a few other small tweaks.

# Changes

- [x] consistent localStorage key for prerelease banner
- [x] reuse firstUnread hook
- [ ] virtual scroller performance enhancements
  - [ ] larger initial page load to reduce future queries
  - [ ] detect high acceleration and pause / prefetch higher amounts
- [ ] refactor channel prefetches: prioritize the last selected channel (recent-chan in localStorage), then defer the rest

2022-11-18 17:15 UTC, patosullivan approved these changes
Looks good and runs well locally.

2022-11-18 17:15 UTC, patosullivan commented on ui/src/logic/usePrefetchChannels.ts
> +    // defer the rest, in batches
Thank you!

2022-11-18 21:12 UTC, arthyn requested changes
Testing this is giving me some really bad behavior just putting this here now before I can write it all out

2022-11-18 22:38 UTC, arthyn commented
So I haven't been able to capture this on camera, but in either watercooler or urbit app dev, on a fresh reload, if you scroll up as soon as you see messages and then scroll up again once the second set of messages load, sometimes you get stuck in like a purgatory of sorts where messages are almost all missing and going either up or down scrolls in the wrong direction.

Other than that, it seems like scrolling backwards now gets stuck more often than before.

2022-11-18 23:46 UTC, tomholford commented
@arthyn Okay thanks, will look into this

2022-11-21 21:47 UTC, arthyn approved these changes

2022-11-21 21:47 UTC, merged