sidebar: scroll changed, background location match added
tloncorp/landscape-apps pull request #1222
Opened 2022-11-22 05:03 UTC by rcrdlbl

see: #1185.

also see: #1202
we needed to also see if the background location was a match for being "in a group" to prevent modals that weren't underneath a group-specific route from launching the sidebar over to the main view.

2022-11-22 15:06 UTC, patosullivan commented
Looking funky on mobile:
![image](https://user-images.githubusercontent.com/1221094/203348700-d38d53cf-f959-4598-9dcb-e170df707c59.png)

2022-11-22 15:07 UTC, patosullivan commented
Also seeing a lot of extra space + unnecessary scrollbar when pinning just one group on desktop:
![image](https://user-images.githubusercontent.com/1221094/203348955-b0c81016-04dd-4d13-a682-32ba9d99edd1.png)

2022-11-22 15:08 UTC, patosullivan requested changes
Seeing some issues with the way this is rendering when a group is pinned on mobile or desktop.

2022-11-22 20:48 UTC, rcrdlbl commented
@patosullivan can you check now? should be fixed

2022-11-23 00:29 UTC, arthyn requested changes

2022-11-23 00:29 UTC, arthyn commented on ui/src/nav/MobileRoot.tsx
> +        <li className="-mx-2 mt-5 grow border-t-2 border-gray-50 pt-3 pb-2">
```suggestion
        <li className="-mx-2 sm:mt-5 grow border-t-2 border-gray-50 pt-3 pb-2">
```

2022-11-23 00:29 UTC, arthyn commented on ui/src/nav/MobileRoot.tsx
> +          <ul className="mb-3 space-y-2 px-2 sm:mb-2 sm:space-y-0 md:mb-0">
You added horizontal padding here but I think it needs go up one level to nav

2022-11-23 17:58 UTC, patosullivan commented
Still seeing some weirdness:
![image](https://user-images.githubusercontent.com/1221094/203616798-11b23e30-b285-442f-aab4-40fe7f81dffa.png)
![image](https://user-images.githubusercontent.com/1221094/203616831-3b563423-cf5a-490c-bbc9-4202f8cdbd6a.png)

2022-11-23 23:55 UTC, rcrdlbl commented
@patosullivan are you sure you've pulled the latest commit? I'm unable to replicate the horizontal scrollbars or menu misalignment anymore on chrome mobile view or my macbook's iOS simulator
<img width="346" alt="Screen Shot 2022-11-23 at 6 53 36 PM" src="https://user-images.githubusercontent.com/40729534/203665326-bfc9463f-e33f-49d0-bd99-967144e177d3.png">

2022-11-24 17:29 UTC, patosullivan approved these changes
Looks good! I must not have pulled last time.

2022-11-28 17:35 UTC, merged