ux: Leap
tloncorp/landscape-apps pull request #1309
Opened 2022-12-05 18:51 UTC by tomholford

# Preview

https://user-images.githubusercontent.com/16504501/205718442-9c12385e-435e-4694-a71b-aa21c37fd856.mp4

# TODO

- [ ] add MacOS shortcut
- [ ] fix the modal at a higher vh so it can expand downwards (a la Groups 1), instead of vertically centered

2022-12-06 06:15 UTC, ryjm commented
👑 this is awesome

what's the likelihood of turning this into a more generic thing that we can use in other apps? would love to be able to implement this in seer/citadel

2022-12-06 12:31 UTC, jamesacklin commented
Also see `lf/search` for additional fun

2022-12-06 18:44 UTC, ryjm commented
> Also see `lf/search` for additional fun

you had me at `lf`

2022-12-12 16:35 UTC, urcades commented
This is excellent work — I'm excited to begin reincorporating Leap in an intentional manner as we get time.

While we've been cooking up updates to Groups/Landscape writ large, we've pushed some edits to the overall Leap structure:

![Screenshot 2022-12-12 at 11 30 26 AM](https://user-images.githubusercontent.com/1195363/207100000-2296ef92-b75b-4f34-aee9-7ef102e80a8b.png)

In @tomholford 's video, the current interface covered are the in-app commands list, but ideally we'd like to generalize + provide affordances for recently-viewed resources across app types — in Groups, we'd want to surface recent groups and channels, while in Talk, we'd want to surface recent conversations or files/links shared in conversations. 

For an initial release, we can shed these sections/features of course, but it's worth noting that Leap was always designed to accommodate more general search-like capabilities for power user types.

Accessing Leap/Search should happen by keystroke, as Tom has already implemented, but in line with this more "General Search Affordance" direction we'd like to take leap, we should surface it clearly in the nav bar of Groups:

![Screenshot 2022-12-12 at 11 34 03 AM](https://user-images.githubusercontent.com/1195363/207100877-ea3418af-c7bf-4a96-8e85-3c367b5afa89.png)

It's worth noting that the eventual intention for most search affordances we provide to just be the universal Leap invocation, filtered/scoped down to the appropriate context.

2023-02-08 23:25 UTC, tomholford commented
@jamesacklin Thanks for the aesthetique aenhancements. Marked as Ready for Review :rocket:

2023-02-08 23:26 UTC, urcades commented
What did we end up deciding for the default keyboard invocation for the interface? `Cmd + K`?

2023-02-09 15:54 UTC, jamesacklin commented
Further enhancements:

- Input respects dark mode
- Truncate long subtitles
- De-emphasize substring match in results

![image](https://user-images.githubusercontent.com/748181/217865427-2ed3345b-d8d3-42a0-b888-293647b42d21.png)

2023-02-09 18:42 UTC, urcades requested changes
Honestly I could have gone in and edited this file myself but I have way too much stuff being juggled right now

2023-02-09 18:42 UTC, urcades commented on ui/src/components/Leap/Leap.tsx
> +        <div className="mt-4 overflow-hidden rounded-lg bg-white">
Small 2¢ I mentioned in the google meet today: it'd be good to close the gap here to `mt-2`

2023-02-09 20:22 UTC, jamesacklin commented
Now has a Talk-specific set of defaults:

![image](https://user-images.githubusercontent.com/748181/217928437-2d58ee6c-faae-489a-b30a-ffc37b544e12.png)

2023-02-09 20:31 UTC, urcades approved these changes
Can't wait to get this back in — Stamp 🫡

2023-02-09 20:51 UTC, arthyn approved these changes
lgtm, you may want to use patrick's new usenavigatebyapp may simplify a lot

2023-02-09 20:51 UTC, arthyn commented on ui/src/components/Leap/useLeap.ts
> +            navigate(`/groups/${groupFlag}/channels/${nest}`);
this will not navigate to the right place if you're in talk and choose a diary/heap

2023-02-09 20:51 UTC, arthyn commented on ui/src/components/Leap/useLeap.ts
> +  ];
this is a little wild haha, but let's just go with it for now

2023-02-09 20:53 UTC, merged