notebooks: virtualize list of notes
tloncorp/landscape-apps pull request #1554
Opened 2022-12-16 19:16 UTC by rcrdlbl

see: #1458.

also fixes an issue with the `sampleQuippers` hook

note that the autoloading in the grid view is still somewhat janky, but it does work

2023-01-03 21:25 UTC, arthyn requested changes
Just a few small nits, otherwise looks good

2023-01-03 21:25 UTC, arthyn commented on ui/src/diary/DiaryChannel.tsx
> +// const ListViewItem = React.memo((letter: DiaryLetter, time: bigInt.BigInteger) => <DiaryListItem letter={letter} time={time} key={time.toString()} />);
```suggestion
```

2023-01-03 21:25 UTC, arthyn commented on ui/src/diary/DiaryChannel.tsx
> +  // }, [chFlag]);
```suggestion
```

2023-01-03 21:25 UTC, arthyn commented on ui/src/diary/DiaryChannel.tsx
> +  const loadOlderNotes = async () => {
use useCallback

2023-01-04 18:36 UTC, rcrdlbl commented
should be cleared up now @arthyn

2023-01-04 19:27 UTC, arthyn approved these changes
lgtm

2023-01-04 19:27 UTC, merged