fixed omission of channel group on json
tloncorp/landscape-apps pull request #1594
Opened 2022-12-28 09:18 UTC by polwex

When scrying through the airlock, `diary` and `heap` channels were not showing the groups they belong to. That makes interop very hard. Please consider merging.

2023-01-02 08:03 UTC, tomholford commented on desk/lib/diary-json.hoon
> +        group/(flag group.p)
```suggestion
        flag/(flag group.p)
```

2023-01-02 08:03 UTC, tomholford commented on desk/lib/heap-json.hoon
> +        group/(flag group.p)
```suggestion
        flag/(flag group.p)
```

2023-01-02 08:05 UTC, tomholford requested changes
Thanks for the PR, this will be useful for other integrations. Requested a minor rename inline (`group` > `flag`). Also, please update the corresponding `DiaryPerm` and `HeapPerm` Typescript types in `ui/src/types/diary.ts` and `ui/src/types/heap.ts`. Otherwise LGTM

2023-01-02 17:23 UTC, arthyn commented
@tomholford we probably should stay with `group` as the key to stay consistent with chat. Also makes it more clear what it's for.

2023-01-19 05:06 UTC, tomholford commented
@arthyn I addressed the PR feedback from both of us so we can close this one out. PTAL at your convenience

2023-01-19 15:26 UTC, tomholford commented
@jamesacklin Per discussion in standup, this PR does not need a state migration since it is not modifying any types. Good for merge upon approval

2023-01-19 15:26 UTC, tomholford approved these changes
LGTM

edit: @arthyn since I made some changes, PTAL at your convenience

2023-01-19 16:26 UTC, merged