groups: only show 'mark as read' if unreads exist
tloncorp/landscape-apps pull request #1654
Opened 2023-01-06 22:15 UTC by jamesacklin

On the tin. Only shows the "Mark All as Read" button in groups/notifications if there are any actual unread notifications.

2023-01-06 22:35 UTC, arthyn requested changes
I think you can simplify this a little

2023-01-06 22:35 UTC, arthyn commented on ui/src/notifications/Notifications.tsx
> +  }, [notifications]);
```suggestion
  const { notifications, count } = useNotifications(flag);
  const hasUnreads = count > 0;
```

2023-01-06 23:27 UTC, jamesacklin commented
Haha, I think I probably could :)

2023-01-09 17:03 UTC, arthyn approved these changes
lgtm

2023-01-09 17:03 UTC, merged