chat: add replies
tloncorp/landscape-apps pull request #1915
Opened 2023-02-10 18:08 UTC by patosullivan

fixes #1747

Adds replies to the main chat input in chat channels. DMs and threads excluded.

https://user-images.githubusercontent.com/1221094/218164649-745b6296-841b-43ee-a9e9-4956a54e9910.mov

2023-02-10 20:09 UTC, urcades commented
Before I get to reviewing — is this an intentionally-downscoped + MVP iteration of replies to get back to parity with the previous version of Groups? As I recall, "replies" in Groups1 were similarly structured as:

- reference to OP's replied-to post
- OP mention
- insertion point added after mention

Which is what this PR appears to be doing

2023-02-10 20:13 UTC, patosullivan commented
> Before I get to reviewing — is this an intentionally-downscoped + MVP iteration of replies to get back to parity with the previous version of Groups? As I recall, "replies" in Groups1 were similarly structured as:
> 
> * reference to OP's replied-to post
> * OP mention
> * insertion point added after mention
> 
> Which is what this PR appears to be doing

yep, that was my goal here.

2023-02-10 20:18 UTC, patosullivan commented
I think in a future sprint we could come back through and style this appropriately (and add appropriate notifications without requiring the mention, which may require storing "replies" in a new way on the backend since we currently use that field for thread replies and we're going to start filtering those out on initial load of a chat channel).

2023-02-10 20:53 UTC, urcades requested changes
This is functionally excellent, and the only request I'd have is for us to ensure that the elements I'm pointing between with a red arrow are spaced out similarly to the area indicated by the green measure:

![Screenshot 2023-02-10 at 3 16 50 PM](https://user-images.githubusercontent.com/1195363/218189302-a8fbaf16-95fd-45b8-8090-a9f109f8df9f.png)

If we're willing to slightly update the reference element/component in order to make replies more legible, I'd recommend we also make the reference metadata more visually diminutive:

![Section 1](https://user-images.githubusercontent.com/1195363/218195352-08eef7cc-86b8-42d9-8639-67d9af1ff405.png)

^ This is a side-by-side comparison of the existing reference component, and margin + element sizing updates we could potentially make so that replies are a little easier to read. If updating the reference element is out of scope, I can place these notes into a new issue for later.

2023-02-10 21:47 UTC, patosullivan commented
> This is functionally excellent, and the only request I'd have is for us to ensure that the elements I'm pointing between with a red arrow are spaced out similarly to the area indicated by the green measure:
> 
> ![Screenshot 2023-02-10 at 3 16 50 PM](https://user-images.githubusercontent.com/1195363/218189302-a8fbaf16-95fd-45b8-8090-a9f109f8df9f.png)
> 
> If we're willing to slightly update the reference element/component in order to make replies more legible, I'd recommend we also make the reference metadata more visually diminutive:
> 
> ![Section 1](https://user-images.githubusercontent.com/1195363/218195352-08eef7cc-86b8-42d9-8639-67d9af1ff405.png)
> 
> ^ This is a side-by-side comparison of the existing reference component, and margin + element sizing updates we could potentially make so that replies are a little easier to read. If updating the reference element is out of scope, I can place these notes into a new issue for later.

I think these are all doable.

2023-02-13 12:47 UTC, patosullivan commented
Hey @urcades, I made the sigil much smaller and added the 16px padding everywhere, let me know what you think:

![image](https://user-images.githubusercontent.com/1221094/218461557-763050c7-8824-42d9-b700-9ca2fd8bb39b.png)

2023-02-13 15:08 UTC, urcades commented
16pt padding on the message itself is great,  the last edit i’d make here is to clamp down the vertical margin (red) on the reference author element, making it equivalent to the left margin (green):

![Uploading 8E83FE66-4693-40BF-A949-3E9AE9AC11F7.jpeg…]()

2023-02-13 15:10 UTC, urcades commented
16pt padding on the message itself is great,  the last edit i’d make here is to clamp down the vertical margin (red) on the reference author element, making it equivalent to the left margin (green):

![37AA53B0-6520-49DC-A0DF-C683DD3F7D3A](https://user-images.githubusercontent.com/1195363/218495435-11499835-e933-4604-8296-5b2cd4194764.jpeg)

2023-02-13 15:19 UTC, patosullivan commented
> 16pt padding on the message itself is great, the last edit i’d make here is to clamp down the vertical margin (red) on the reference author element, making it equivalent to the left margin (green):
> 
> ![37AA53B0-6520-49DC-A0DF-C683DD3F7D3A](https://user-images.githubusercontent.com/1195363/218495435-11499835-e933-4604-8296-5b2cd4194764.jpeg)

Done:
![image](https://user-images.githubusercontent.com/1221094/218497714-2464594e-84ff-41ab-9965-8ba6f8a3de79.png)

2023-02-13 16:51 UTC, urcades approved these changes
🫡

2023-02-13 21:32 UTC, arthyn approved these changes
lgtm, one question and we just need to remember that we'll need to rip a lot of this out when we implement these through the backend

2023-02-13 21:32 UTC, arthyn commented on ui/src/chat/ChatInput/ChatInput.tsx
> +  const replyingWrit = chatReplyId && pact.writs.get(pact.index[chatReplyId]);
Unclear why we needed to replace the chat store behavior with routing. It seems the same?

2023-02-14 01:28 UTC, merged