chat: add embed content
tloncorp/landscape-apps pull request #1932
Opened 2023-02-14 12:56 UTC by patosullivan

A first stab at embed content. @urcades I just did this off the cuff, let me know what you think.

Only supports youtube, twitter, spotify, and direct audio links for now.

https://user-images.githubusercontent.com/1221094/218745164-4965430f-f237-4636-b219-b841eeb5679f.mov

https://user-images.githubusercontent.com/1221094/218745175-f34b96bd-2501-4b87-8c8e-fe50ec8bf3bc.mov

2023-02-14 14:42 UTC, tomholford approved these changes
Pulled and tested this locally. Working as expected:

<img width="569" alt="image" src="https://user-images.githubusercontent.com/16504501/218770605-8d298ad1-75c9-40bf-8c99-ebeb37826fc1.png">

2023-02-22 23:24 UTC, arthyn commented
@urcades were you ever able to give this a look?

2023-02-23 15:43 UTC, urcades requested changes
@arthyn finally getting around to it!

This functionally is looking fantastic — if we wanted to perform a few more stylistic/surface-level tweaks, I'd only recommend we style the lightbox interface as such (with close button anchored to the edge of the viewport), so that we don't get too much interference between the close/X button and any interfaces/buttons located within the embed itself:

<img width="3200" alt="Lightbox" src="https://user-images.githubusercontent.com/1195363/220955253-ba180337-617b-4d75-b81d-1dcc48da064d.png">

One other tiny detail we can stand to tweak is the bottom padding/spacing of the embed's metadata row:

<img width="817" alt="Screenshot 2023-02-23 at 10 38 21 AM" src="https://user-images.githubusercontent.com/1195363/220955873-c65bcbf7-3ae2-40a5-b852-62e0060d23b9.png">

Note the uneven blue boxes here indicating the element spacing — we should tuck in the vertical spacing a bit such that it's equivalent to the horizontal spacing, and equidistant all around the embed contents.

Other than these tweaks, I only have a few questions:

In the included update, is there a way to play embeds within the chat, or must a lightbox be opened every time to view/play the embed content?

How does one view the source material each embed points to? Is this possible via the metadata text underneath the embed content? Through the lightbox view of the embedded content?

Since we're implementing a lightbox view here, would it be possible to apply the same styling to plain images posted "natively" to a talk channel? It'd be great if we could simply make lightboxing a regular pattern for all media posted to a talk channel, or to notebooks, etc.

2023-02-23 22:20 UTC, patosullivan commented
After merging master into this branch something is up with the audio player component. It's constantly re-rendering after a scroll. Is this a VS issue? @arthyn

2023-02-24 20:13 UTC, patosullivan commented
Hey @urcades,

Yes, they need to be rendered outside of the virtual scroller to avoid having the scroller redraw and jump around.

I've updated the spacing, looks like this now:

![image](https://user-images.githubusercontent.com/1221094/221281602-d9464199-d6bb-414e-91c4-2dd889447673.png)

I've also created a new light box component that we could use anywhere in the app, looks like this:
![image](https://user-images.githubusercontent.com/1221094/221281772-5211d0ce-df0b-47bb-89c7-cec8b4e63f4a.png)

I can add some functionality to show images in the light box pretty easily too, commit incoming.

2023-02-24 20:22 UTC, patosullivan commented
Ok, added the light box in for images:


https://user-images.githubusercontent.com/1221094/221283899-3fa261e3-23b8-4ac4-ab84-8d3564354307.mov

2023-02-24 20:23 UTC, patosullivan commented
> How does one view the source material each embed points to? Is this possible via the metadata text underneath the embed content? Through the lightbox view of the embedded content?

I made the title for the embeds a clickable link, but I've also now added the "Source" button from your mocks which is a link to the source material.

2023-02-27 21:19 UTC, urcades approved these changes
Updates look fantastic, thanks for answering the Qs!

2023-02-27 22:58 UTC, arthyn requested changes
buttons!

2023-02-27 22:58 UTC, arthyn commented on ui/src/chat/ChatEmbedContent/YouTubeEmbed.tsx
> +      <div
Should be button

2023-02-27 22:58 UTC, arthyn commented on ui/src/chat/ChatEmbedContent/SpotifyEmbed.tsx
> +      <div
Should be button

2023-02-27 22:58 UTC, arthyn commented on ui/src/chat/ChatContent/ChatContentImage.tsx
> +          onClick={() => setShowLightBox(true)}
Probably should wrap the image in a transparent button with this onclick

2023-02-28 15:12 UTC, merged