chat: thread status cosmetics
tloncorp/landscape-apps pull request #2005
Opened 2023-02-25 15:11 UTC by jamesacklin

Fixes some alignment issues in the chat thread indicator that have been annoying me for some time.

1. Properly aligns the left edge of the first avatar in series with the emoji/message content above.
2. Lightly overlaps sigils to conserve horizontal real estate. The masking effect is sensitive to hovered/active/linked states of both the thread indicator and the parent message.
3. Hides the "Last reply " prefix text on small screens and correctly capitalizes the relative date string in its absence.

![image](https://user-images.githubusercontent.com/748181/221364579-d76bbc30-6d26-45fe-b662-b690c91b2232.png)

2023-02-25 15:33 UTC, patosullivan approved these changes
Lgtm

2023-02-27 15:56 UTC, arthyn commented on ui/src/styles/components.css
> +}
Doesn't really follow the way we've been conditionally applying classes I would move into JS

2023-02-27 17:17 UTC, urcades requested changes
One tiny change I'd suggest we make is to move the "unread dot" over to a position that's a little more representative of how we surface the dot elsewhere (right-aligned to its container + object of attention):

![Screenshot 2023-02-27 at 12 15 51 PM](https://user-images.githubusercontent.com/1195363/221633212-81be3f67-6a5b-44de-98b3-6ca950d321db.png)

This also has the benefit of keeping the "new replies" row visually left-aligned with the text it's coupled to.

2023-02-27 21:40 UTC, jamesacklin commented
@urcades:

With unreads:

![image](https://user-images.githubusercontent.com/748181/221691276-c9e079e1-13db-4ec9-b43d-18b0ae2f7d00.png)

At rest:

![image](https://user-images.githubusercontent.com/748181/221691499-c180ac90-5e8b-42e0-baad-2bb55707d664.png)

2023-02-27 22:05 UTC, merged