contacts: replacing contact-store/hook
tloncorp/landscape-apps pull request #2189
Opened 2023-03-24 13:59 UTC by joemfb

Fixes #1305.

- [ ] update frontend to support (new) new interface
- [ ] reflect subscription state in json conversions ("stale" flag)
- [ ] remove contacts on breach
- [ ] moar livenet testing

2023-04-03 18:15 UTC, patosullivan commented
Seeing an issue where changes to a ships own profile don't seem to update for the user:

https://user-images.githubusercontent.com/1221094/229592885-954e659b-373f-46d2-820c-a0ff36be8f0b.mov

2023-04-03 19:43 UTC, jamesacklin commented
Check the agent it's subscribing to? Since we're in this interim state, things might not be 100% hooked up.

Does %dbug state show the change?

2023-04-10 22:12 UTC, philipcmonk requested changes
I have not reviewed any typescript, but the hoon looks good except this one thing that needs to be fixed.

2023-04-11 02:25 UTC, jamesacklin commented
Excellent, thank you @philipcmonk

@arthyn Are you good to make this change or do you want to tag someone in?

2023-04-11 05:03 UTC, joemfb commented on desk/app/contacts.hoon
> +    =/  ful  .^(rolodex:legacy gx+(weld bas /all/noun))
Oh man, I'm never gonna live this down ...

A self-poke should be enough to get out of the danger zone, right? The same event is fine, so long as all the apps have upgraded first?

2023-04-11 05:24 UTC, philipcmonk commented
Oh right, that's correct

On Mon, Apr 10, 2023, 22:03 Joe Bryan ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In desk/app/contacts.hoon
> <https://github.com/tloncorp/landscape-apps/pull/2189#discussion_r1162304349>
> :
>
> > +    ?.  .^(? gu+bas)  cor
> +    =/  ful  .^(rolodex:legacy gx+(weld bas /all/noun))
>
> Oh man, I'm never gonna live this down ...
>
> A self-poke should be enough to get out of the danger zone, right? The
> same event is fine, so long as all the apps have upgraded first?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tloncorp/landscape-apps/pull/2189#discussion_r1162304349>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABKLYGCPXLQ2B3VLWXS7MXDXATQ33ANCNFSM6AAAAAAWGTHKU4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-11 15:26 UTC, jamesacklin commented on desk/app/contacts.hoon
> +    =/  ful  .^(rolodex:legacy gx+(weld bas /all/noun))
https://github.com/tloncorp/landscape-apps/pull/2189#issuecomment-1502705775

2023-04-12 18:36 UTC, philipcmonk approved these changes
Looks good

2023-04-12 18:38 UTC, merged