groups: lures for lure
tloncorp/landscape-apps pull request #2191
Opened 2023-03-24 22:28 UTC by arthyn

This adds an entry into the invite people dialog screen so that people now see that they can invite others whether on urbit or off. This combines the editor in the previous PR with display so that the host can enable from either location. This also pulls the "invite people" link up into the group sidebar so it's more present. There are more locations in @urcades onboarding figma, but I thought we should just get this going first.

Also refactors the way we do dialogs so that there's less componentry to use out the gate and cleans up our scrollbars so they're transparent except for the thumb.

<img width="754" alt="Screen Shot 2023-03-24 at 5 26 22 PM" src="https://user-images.githubusercontent.com/5466421/227654666-2a285dd1-779b-45bd-8cf2-44917a287aa9.png">

**host**
<img width="857" alt="Screen Shot 2023-03-24 at 5 26 13 PM" src="https://user-images.githubusercontent.com/5466421/227654574-3b6a32c6-a6b3-44cb-b1c6-aaeef1d844f6.png">

<img width="862" alt="Screen Shot 2023-03-24 at 5 25 58 PM" src="https://user-images.githubusercontent.com/5466421/227654587-f0b0a902-78f3-4a68-a7ee-389511821b6d.png">

**member**

<img width="873" alt="Screen Shot 2023-03-24 at 5 26 29 PM" src="https://user-images.githubusercontent.com/5466421/227654634-b292f74a-8f62-4bb7-8306-ad596a41b92b.png">
<img width="921" alt="Screen Shot 2023-03-24 at 5 26 55 PM" src="https://user-images.githubusercontent.com/5466421/227654647-b6ef5dd5-f2af-4809-8b6d-3898348adc01.png">

2023-03-27 16:11 UTC, zalberico requested changes
I think the invite headers could be clearer, but I like the separate modal and where you have the link in the sidebar.

> Send Landscape Invite to Someone

I'd probably change this to: Send Invite Link to Friends Not on Urbit

> Invite people to group

I'd change this to: Send Invite to Friends Already on Urbit

Thoughts?

2023-03-27 18:36 UTC, urcades commented
Here's a set of suggestions, and an interface to grant them some context:

---

NEW — **Invite someone from outside the Urbit network**
Courtesy of Tlon Corporation

Have friends, family or collaborators who aren’t on Urbit? You can now gift them an Urbit ID and onboard them to your group all in one free and easy sweep. Just copy and share the link below. 

---

**Invite by Urbit ID** 
(e.g. ~sampel-palnet) or display name. 
[Search]

---

Interface Example:

<img width="1440" alt="Invite to Group Modal" src="https://user-images.githubusercontent.com/1195363/228034990-026d9a1d-1382-4ba5-9ffe-6a242959ba24.png">

2023-03-27 19:24 UTC, arthyn commented
updated to look like this: 
![Screen Shot 2023-03-27 at 2 17 07 PM](https://user-images.githubusercontent.com/5466421/228045579-bfe2bcde-0dd9-40b8-aa22-22232e281544.png)

2023-03-27 23:19 UTC, patosullivan approved these changes
Looks good! Just one style related comment, but I'm probably missing something.

2023-03-27 23:19 UTC, patosullivan commented on ui/src/dms/MessagesSidebar.tsx
> -    <nav className="flex h-full w-64 flex-none flex-col border-r-2 border-gray-50 bg-white">
Why make this full?

2023-03-28 12:29 UTC, jamesacklin approved these changes
Degrades nicely if you don't have lure support installed (or the group host doesn't have it turned on).

2023-03-28 16:19 UTC, zalberico approved these changes
Thanks - Let's ship it!

2023-03-28 16:19 UTC, merged

2023-03-28 17:07 UTC, arthyn commented on ui/src/dms/MessagesSidebar.tsx
> -    <nav className="flex h-full w-64 flex-none flex-col border-r-2 border-gray-50 bg-white">
bah I saw this comment and forgot lol