Po/add react query
tloncorp/landscape-apps pull request #2233
Opened 2023-03-31 20:41 UTC by patosullivan

2023-04-04 18:18 UTC, patosullivan commented
Ok, I think this is ready to go @arthyn

2023-04-04 18:30 UTC, arthyn commented
cool I'm about halfway through

2023-04-04 20:11 UTC, patosullivan commented
Looking into an issue with the "Mark All as Read" button rn.

2023-04-04 20:23 UTC, arthyn requested changes
There's a few issues here that we should probably address. Other things to consider are more big picture like making subscription tracking have some default so we don't have to always have the giant check and also giving all our queries initial data so that we don't have to do as much "safe" dereferencing.

2023-04-04 20:23 UTC, arthyn commented on ui/src/app.tsx
> +    groups !== undefined ? (_.isEmpty(groups) ? false : true) : true;
```suggestion
    groups !== undefined ? !_.isEmpty(groups) : true;
```

2023-04-04 20:23 UTC, arthyn commented on ui/src/state/groups/groups.ts
> +    throw new Error('Failed to fetch group index');
when used like a normal hook this means if it fails we'll hit the error boundary and they'll have to refresh

2023-04-04 20:24 UTC, arthyn commented on ui/src/components/References/GroupReference.tsx
> +  const preview = useGangPreview(flag, isScrolling);
maybe not, the way you handled here is fine

2023-04-04 20:53 UTC, patosullivan commented on ui/src/app.tsx
> +            persister: indexedDBPersistor(`${window.our}-${app}`),
good idea

2023-04-04 20:54 UTC, patosullivan commented on ui/src/state/hark.ts
> +      await queryClient.cancelQueries(['carpet', variables.rope.group]);
fixed in my latest commit

2023-04-04 20:56 UTC, patosullivan commented on ui/src/groups/GroupAdmin/GroupInfoEditor.tsx
> +        if (editStatus === 'success' || privacyChanged) {
Will look into it.

2023-04-05 11:15 UTC, patosullivan commented on ui/src/groups/FindGroups.tsx
> +      const results: GroupIndex | null = data;
yeah, idk why this is there. might have had some idea and then backed out of it, didn't clean this part up.

2023-04-05 11:30 UTC, patosullivan commented on ui/src/groups/GroupAdmin/GroupInfoEditor.tsx
> +        if (editStatus === 'success' || privacyChanged) {
Passed it to the onSuccess callback.

2023-04-05 21:49 UTC, arthyn approved these changes
lgtm, just the two nits then gtg

2023-04-05 21:49 UTC, arthyn commented on ui/src/logic/useReactQuerySubscription.tsx
> +    await useSchedulerStore.getState().wait(
```suggestion
    useSchedulerStore.getState().wait(
```

2023-04-05 21:49 UTC, arthyn commented on ui/src/logic/useReactQuerySubscribeOnce.tsx
> +      }, 5000);
May want to open this up as a parameter

2023-04-06 11:17 UTC, patosullivan commented on ui/src/logic/useReactQuerySubscribeOnce.tsx
> +      }, 5000);
done

2023-04-06 11:33 UTC, merged