notebooks: switch to react-query
tloncorp/landscape-apps pull request #2538
Opened 2023-05-22 14:32 UTC by patosullivan

Fixes #2241 and makes working with notes much snappier/more reliable in general

2023-05-23 21:21 UTC, arthyn requested changes
this is great, we're seeing more how react query flexes. it'd be nice if we can find some shortcuts to slim up optimistic updates. possibly using produce from immer?

2023-05-23 21:21 UTC, arthyn commented on ui/src/state/diary/diary.ts
> +      if (prevNote) {
we should probably wrap this up in a function since we're doing it over and over and just have it accept some update function that returns a new note

2023-05-25 17:43 UTC, patosullivan commented on ui/src/state/diary/diary.ts
> +    path: `/diary/${flag}/notes/older/${fetchStart}/${count}`,
yeah, I'll update the peek case in lib/notes.hoon

2023-05-25 17:49 UTC, patosullivan commented on ui/src/state/diary/diary.ts
>  export function useDiaryPerms(flag: DiaryFlag) {
yep, good idea.

2023-05-25 17:53 UTC, patosullivan commented on ui/src/state/diary/diary.ts
> +      await queryClient.refetchQueries(['diary', 'notes', variables.flag]);
We actually only use this in one spot, I think I'm gonna ditch it.

2023-05-30 17:33 UTC, arthyn approved these changes
lgtm

2023-05-30 17:35 UTC, merged