notebooks: add markdown checkboxes
tloncorp/landscape-apps pull request #2838
Opened 2023-08-29 18:40 UTC by patosullivan

Fixes LAND-756.

Looks like this:

https://github.com/tloncorp/landscape-apps/assets/1221094/18acd3e2-663a-4ff2-be3e-9cc8ef542c41

2023-08-29 20:43 UTC, latter-bolden commented
Ran into some funk while testing:

- Inserting a Task List seems to remove other content in the note
- Task Lists don't seem to persist when saved (not seeing them in the view or edit screens for the saved note)


https://github.com/tloncorp/landscape-apps/assets/90741358/0af7901d-47c3-4ba2-8486-554c0039a1a6

2023-08-30 11:58 UTC, patosullivan commented
Yeah, realized this would be an issue right as I was falling asleep last night, ha.

2023-08-30 18:04 UTC, patosullivan commented
Updated so that we can persist tasklists/taskitems to the backend and render them in notes. Not sure if we need a state transition here or not.

2023-08-31 13:43 UTC, arthyn requested changes
lgtm, won't need a state transition I think, but will need a version update.

2023-08-31 13:43 UTC, arthyn commented on ui/src/diary/DiaryContent/DiaryContent.tsx
> +          aria-disabled
maybe also add an aria label of checked/unchecked?

2023-09-05 15:17 UTC, arthyn approved these changes
lgtm

2023-09-05 15:17 UTC, merged