groups: allow users to block other users from DMing them
tloncorp/landscape-apps pull request #2898
Opened 2023-09-29 14:52 UTC by patosullivan

Fixes LAND-914, adds a `blocked` set of ships to state on %chat and associated marks/pokes/scry/UI elements.

If we hear a dm-action update from a blocked ship we ignore it.

https://github.com/tloncorp/landscape-apps/assets/1221094/7bd7a0e2-5889-4c4e-acb2-e81428d40374

2023-09-29 15:10 UTC, arthyn requested changes

2023-09-29 15:10 UTC, arthyn commented on desk/app/chat.hoon
> +      ~|("%dm-action poke failed: ship blocked" !!)
need to add this check to `di-take-counter` which is where we normally receive dms from other parties. this route is more for ourselves.

2023-09-29 15:10 UTC, arthyn commented on desk/app/chat.hoon
> +    [%x %blocked ~]  ``chat-blocked-ships+!>(blocked)
```suggestion
    [%x %blocked ~]  ``ships+!>(blocked)
```

2023-09-29 15:10 UTC, arthyn commented on desk/mar/chat/blocked-ships.hoon
> +/-  c=chat
can delete this guy we already have a ships mark

2023-09-29 15:15 UTC, arthyn commented on desk/app/chat.hoon
> +      ~|("%dm-action poke failed: ship blocked" !!)
oh nvm I see you put it later

2023-09-29 15:26 UTC, zalberico commented
From Sync, example of unblock profile from twitter:
<img width="686" alt="Screenshot 2023-09-29 at 8 23 30 AM" src="https://github.com/tloncorp/landscape-apps/assets/441466/fbf322d1-e9f3-49e6-bf0c-ee916fdbe4a1">

They also have a list of blocked users to unblock in settings.

It's also important for the person who is blocked to know they can't dm (helps reduce abuse - if someone knows they can't message on the platform them they won't, if they think they can then things can escalate with them getting crazier thinking the person is seeing their messages).

2023-10-02 11:17 UTC, patosullivan commented
I added an unblock button to the "You have blocked this user" text shown in place of the chat input: 

![image](https://github.com/tloncorp/landscape-apps/assets/1221094/0c61b065-7f55-40d5-811b-53d028e2bf45)

2023-10-02 20:57 UTC, patosullivan commented
https://github.com/tloncorp/landscape-apps/assets/1221094/cccbd4f6-6bb1-4bbb-a4f5-322fdca1b513

2023-10-02 23:03 UTC, arthyn approved these changes
lgtm this is great

2023-10-03 15:05 UTC, patosullivan commented
Updated to allow users to know when they've been blocked.


https://github.com/tloncorp/landscape-apps/assets/1221094/f65e7975-b1cd-4f13-8dad-3c59770914fa

2023-10-03 15:11 UTC, jamesacklin commented
Fantastic, thank you.

2023-10-03 15:15 UTC, jamesacklin approved these changes

2023-10-03 15:15 UTC, jamesacklin commented on ui/src/profiles/ProfileModal.tsx
> +            <h2 className="mb-3 font-semibold">Blocked You</h2>
Let's just use "Blocked"

2023-10-03 16:57 UTC, arthyn approved these changes
lgtm

2023-10-03 17:53 UTC, patosullivan commented on desk/lib/chat-json.hoon
> +  ::
I think it's necessary for the subscription facts sent to the frontend, right?

2023-10-03 17:57 UTC, patosullivan commented on desk/lib/chat-json.hoon
> +  ::
nvm I just realized you were commenting on the de-js functions.

2023-10-03 18:06 UTC, merged