Add e2e.md with notes on automated tests
tloncorp/landscape-apps pull request #2999
Opened 2023-11-08 22:36 UTC by mrozanski

@patosullivan feel free to suggest any edits

2023-11-09 14:27 UTC, patosullivan requested changes
Looks good, just needs a few tweaks.

As an aside (not necessary for now), we should also figure out a way to determine if the existing urbit binary in the dist folder is the appropriate version and delete it (then download the new one) if it's old. This only effects developers running the test locally, it'll be fine in CI since it's a new environment on each run.

2023-11-09 14:27 UTC, patosullivan commented on ui/E2E.md
> +npm run rube
```suggestion
npm run e2e
```

We're aliasing it to e2e in case we need to change the underlying script(s) later.

2023-11-09 14:27 UTC, patosullivan commented on ui/E2E.md
> +npm run rube:debug
```suggestion
npm run e2e:debug
```

this one has to be `e2e`.

2023-11-09 14:27 UTC, patosullivan commented on ui/E2E.md
> +2. downlaods the urbit binaries for the local architecture
```suggestion
2. downloads the urbit binaries for the local architecture
```

2023-11-10 00:19 UTC, jamesacklin approved these changes

2023-11-13 21:02 UTC, merged