chat: added DMOptions dropdown to group chat channels
tloncorp/landscape-apps pull request #968
Opened 2022-10-03 22:06 UTC by rcrdlbl

This currently partially solves for #801 

I can send the request to pin a group chat channel, but the backend rejects it (think it'll only take DMs and MultiDMs at this point).

@liam-fitzgerald @arthyn 
mind helping resolve the backend portion of this?

2022-10-25 20:26 UTC, arthyn commented
fixes #801 no actual backend issues, just using the wrong keys

2022-10-27 13:51 UTC, jamesacklin commented
This seems fine, @patosullivan review?

2022-10-27 19:16 UTC, patosullivan requested changes
Looks good, just one issue.

2022-10-27 19:16 UTC, patosullivan commented on ui/src/dms/MessagesSidebarItem.tsx
>        to={`/groups/${groupFlag}/channels/${whom}`}
```suggestion
      to={`/groups/${groupFlag}/channels/${nest}`}
```

If this is set to whom it won't route to the actual channel.

2022-10-27 19:17 UTC, patosullivan approved these changes

2022-10-27 19:22 UTC, merged