sidebar: set active items one shade darker
tloncorp/landscape-apps pull request #977
Opened 2022-10-05 02:15 UTC by rcrdlbl

see: #924.

2022-10-05 02:25 UTC, urcades requested changes
This is very close, with exception to the behavior of hovering over an already-selected item/row in the sidebar — we should probably omit selected rows from the onHover styling treatment, as there's no additional utility gained from hovering over a selected row (in the sense that clicking a selected row won't actually do anything)

To get a rough sense of the feeling we're trying to evoke here, you can check out this figma, and hover/click over any of the **groups** in the sidebar (the other rows don't do anything).

2022-10-05 18:06 UTC, rcrdlbl commented
@urcades updated!

2022-10-05 19:40 UTC, urcades requested changes
The edits I see made to the top nav items in both Groups and Talk are perfect, I only see one last change that needs to be made in the list of DMs/Groups themselves:

https://user-images.githubusercontent.com/1195363/194147824-511e1a4e-bf07-444c-8e7c-d7774cd57d74.mov

You can see in the first part of this  video, the on-hover and highlighting behavior is as-specified, but as I hover the individual DMs, they remain butted up against one another — their onHover styling is perfect though.

All that remains is ensuring the small spacing is inherited by these row items as well!

2022-10-05 19:48 UTC, urcades approved these changes
Ignore the previous comment, @rcrdlbl alerted me to the fact that this PR is simply about the active item shading, not the row spacing.

2022-10-05 20:14 UTC, rcrdlbl commented
The latest commit should address your concern, @urcades

2022-10-06 16:16 UTC, arthyn requested changes
Just the one file to remove, then good to merge

2022-10-06 16:16 UTC, arthyn commented on ui/tsconfig.rvpu8p5fi8d.json
> +{
Remove this file

2022-10-06 16:51 UTC, rcrdlbl commented on ui/tsconfig.rvpu8p5fi8d.json
> +{
Done!

2022-10-06 16:53 UTC, arthyn approved these changes
lgtm

2022-10-06 16:53 UTC, merged