refs: adds desk refs
tloncorp/landscape-apps pull request #990
Opened 2022-10-06 20:33 UTC by nerveharp

- Ports over docket state from garden
- Adds an AppReference component
- Changes the types to reflect changes to desk cites

![image](https://user-images.githubusercontent.com/748181/194412975-307da426-27cc-4fd5-a0f1-d876adeb9c13.png)

fixes tloncorp/homestead#612

2022-10-06 22:07 UTC, arthyn requested changes
Just missing one piece, but this is great!

2022-10-06 22:07 UTC, arthyn commented on ui/src/components/References/AppReference.tsx
> +
missing a call for treaties we don't have:

```
  useEffect(() => {
    if (!treaty) {
      useDocketState.getState().requestTreaty(ship, desk);
    }
  }, [treaty, ship, desk]);
  ```

2022-10-07 19:59 UTC, liam-fitzgerald commented
@nerveharp what's going on with CI?

2022-10-07 20:00 UTC, nerveharp commented
> @nerveharp what's going on with CI?

Test for ChatMessage is borked, @arthyn is looking into it. I'm lost

2022-10-07 20:41 UTC, arthyn approved these changes
works now!

2022-10-07 20:41 UTC, merged